site_name: Project Docs

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.footer
use_directory_urls: false

palette:
  - scheme: slate

extra_css:
  - overrides/extra.css

extra_javascript:
  - overrides/extra.js
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - overrides/init-mermaid.js   # we’ll add this file for init

nav:
  - Home: index.md
  - Spring Boot: 
      - Project Flow:
          - Core: spring-boot/project-flow/core.md
          - MVC Request Flow: spring-boot/project-flow/core2.md
          - Spring Boot Internals: spring-boot/project-flow/core3.md
          - Validation & DTOs: spring-boot/project-flow/core4.md
      - Another Section:
          - Topic 1: another/topic1.md
          - Topic 2: another/topic2.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
