site_name: Project Docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand

# This activates the dark theme, which is required for your CSS to work
palette:
  - scheme: slate

# This path must match the location of your CSS file (docs/css/extra.css)
extra_css:
  - overrides/extra.css

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/install.md
      - Usage: getting-started/usage.md
  - Spring Boot:
      - Overview: spring-boot/overview.md
      - Project Flow:
          - Core: spring-boot/project-flow/core.md
          - MVC Request Flow: spring-boot/project-flow/core2.md
          - Data: spring-boot/project-flow/data.md

# This block is required to enable code syntax highlighting
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

plugins:
  - search
  - mermaid2
